import express from "express";
import path from "path";
import fs from "fs";
import crypto from "crypto";
import jwt from "jsonwebtoken";
import bcrypt from "bcryptjs";
import helmet from "helmet";
import cors from "cors";
import dotenv from "dotenv";
import pg from "pg";
import { fileURLToPath } from "url";

dotenv.config();
const { Pool } = pg;
const __filename=fileURLToPath(import.meta.url);
const __dirname=path.dirname(__filename);
const app=express();
const PORT=Number(process.env.PORT||3000);
const PUBLIC_DIR=path.join(__dirname,"../public");
const CURRICULUM_FILE=path.join(__dirname,"../data","passcogh_carriculum.json");
const JWT_SECRET=process.env.JWT_SECRET;
const CREATOR_EMAIL=String(process.env.CREATOR_EMAIL||"").trim().toLowerCase();
const pool=new Pool({
 connectionString:process.env.DATABASE_URL,
 ssl:process.env.NODE_ENV==="production"?{rejectUnauthorized:false}:undefined
});
app.disable("x-powered-by");
app.use(helmet({crossOriginResourcePolicy:false}));
app.use(cors({origin:process.env.FRONTEND_ORIGIN?process.env.FRONTEND_ORIGIN.split(",").map(x=>x.trim()):true,credentials:true}));
app.use(express.json({limit:"2mb"}));

const q=(text,params=[])=>pool.query(text,params);
const curriculum=()=>{try{return JSON.parse(fs.readFileSync(CURRICULUM_FILE,"utf8"));}catch(e){return {platform:"PASSCOGH-MODOO",levels:[],error:"Curriculum file missing or invalid."}}};
const levels=c=>Array.isArray(c?.levels)?c.levels:Array.isArray(c)?c:[];
const subjects=c=>levels(c).flatMap(l=>(Array.isArray(l.subjects)?l.subjects:Array.isArray(l.courses)?l.courses:[]).map(s=>({...s,level:s.level||l.name||l.id||""})));
const findSubject=v=>{const x=String(v||"").toLowerCase();return subjects(curriculum()).find(s=>String(s.id||s.code||s.name||s.title||"").toLowerCase()===x||String(s.name||s.title||"").toLowerCase()===x)};
const token=u=>jwt.sign({sub:String(u.id),email:u.email,role:u.role},JWT_SECRET,{expiresIn:"7d"});
async function auth(req){const h=req.headers.authorization||"";if(h.startsWith("Bearer ")){try{return (await q("SELECT id,name,email,role,created_at FROM users WHERE id=$1",[jwt.verify(h.slice(7),JWT_SECRET).sub])).rows[0]||null}catch{}}const email=String(req.headers["x-user-email"]||"").trim().toLowerCase();if(email)return (await q("SELECT id,name,email,role,created_at FROM users WHERE email=$1",[email])).rows[0]||null;return null}
async function user(req,res,next){req.user=await auth(req);if(!req.user)return res.status(401).json({success:false,message:"Authentication required."});next()}
async function creator(req,res,next){await user(req,res,()=>{});if(res.headersSent)return;if(req.user.role!=="creator")return res.status(403).json({success:false,message:"Creator access denied."});next()}
async function paystackInit(email,amount,reference,callback_url){if(!process.env.PAYSTACK_SECRET_KEY)throw Error("PAYSTACK_SECRET_KEY is not configured.");const r=await fetch("https://api.paystack.co/transaction/initialize",{method:"POST",headers:{Authorization:`Bearer ${process.env.PAYSTACK_SECRET_KEY}`,"Content-Type":"application/json"},body:JSON.stringify({email,amount:Math.round(Number(amount)*100),currency:"GHS",reference,callback_url})});const d=await r.json();if(!r.ok||!d.status)throw Error(d.message||"Payment initialization failed.");return d.data}
async function paystackVerify(ref){const r=await fetch(`https://api.paystack.co/transaction/verify/${encodeURIComponent(ref)}`,{headers:{Authorization:`Bearer ${process.env.PAYSTACK_SECRET_KEY}`}});const d=await r.json();if(!r.ok||!d.status)throw Error(d.message||"Payment verification failed.");return d.data}

app.get("/api/health",async(req,res)=>{try{await q("SELECT 1");const c=curriculum();res.json({success:true,message:"PASSCOGH-MODOO backend is running",database:"connected",curriculumFileExists:fs.existsSync(CURRICULUM_FILE),curriculumLevels:levels(c).length,paystackConfigured:Boolean(process.env.PAYSTACK_SECRET_KEY),missingRequiredConfig:[!process.env.DATABASE_URL&&"DATABASE_URL",!JWT_SECRET&&"JWT_SECRET"].filter(Boolean)})}catch(e){res.status(503).json({success:false,message:"Database connection failed.",error:e.message})}});
app.post("/api/auth/register",async(req,res)=>{try{const name=String(req.body.name||"").trim(),email=String(req.body.email||"").trim().toLowerCase(),password=String(req.body.password||"");if(!email.includes("@")||password.length<8)return res.status(400).json({success:false,message:"Valid email and password of at least 8 characters are required."});const hash=await bcrypt.hash(password,12),role=CREATOR_EMAIL&&email===CREATOR_EMAIL?"creator":"learner";const r=await q("INSERT INTO users(name,email,password_hash,role) VALUES($1,$2,$3,$4) RETURNING id,name,email,role,created_at",[name,email,hash,role]);res.status(201).json({success:true,user:r.rows[0],token:token(r.rows[0])})}catch(e){res.status(e.code==="23505"?409:500).json({success:false,message:e.code==="23505"?"Email already registered.":"Registration failed."})}});
app.post("/api/auth/login",async(req,res)=>{try{const email=String(req.body.email||"").trim().toLowerCase(),password=String(req.body.password||"");const r=await q("SELECT * FROM users WHERE email=$1",[email]);const u=r.rows[0];if(!u||!u.password_hash||!(await bcrypt.compare(password,u.password_hash)))return res.status(401).json({success:false,message:"Invalid email or password."});const pub={id:u.id,name:u.name,email:u.email,role:u.role,created_at:u.created_at};res.json({success:true,user:pub,token:token(pub)})}catch{res.status(500).json({success:false,message:"Login failed."})}});
app.get("/api/auth/me",user,(req,res)=>res.json({success:true,user:req.user}));

app.get("/api/curriculum",(req,res)=>{const c=curriculum();res.json({success:true,curriculum:c,levels:levels(c),subjectCount:subjects(c).length})});
app.get("/api/levels",(req,res)=>res.json({success:true,levels:levels(curriculum())}));
app.get("/api/subjects",(req,res)=>res.json({success:true,subjects:subjects(curriculum())}));
app.get("/api/subjects/:subject",(req,res)=>{const s=findSubject(req.params.subject);if(!s)return res.status(404).json({success:false,message:"Subject not found."});res.json({success:true,subject:s})});
app.get("/api/subjects/:subject/topics",(req,res)=>{const s=findSubject(req.params.subject);if(!s)return res.status(404).json({success:false,message:"Subject not found."});res.json({success:true,subject:s.name||s.title,topics:s.topics||s.units||[]})});
app.get("/api/subjects/:subject/topics/:topic",(req,res)=>{const s=findSubject(req.params.subject);if(!s)return res.status(404).json({success:false,message:"Subject not found."});const t=(s.topics||s.units||[]).find(x=>String(x.id||x.code||x.name||x.title||"").toLowerCase()===req.params.topic.toLowerCase());if(!t)return res.status(404).json({success:false,message:"Topic not found."});res.json({success:true,subject:s.name||s.title,topic:t})});

app.get("/api/questions",async(req,res)=>{const p=[],w=[];if(req.query.subjectId){p.push(req.query.subjectId);w.push(`subject_id=$${p.length}`)}if(req.query.type){p.push(req.query.type);w.push(`question_type=$${p.length}`)}res.json({success:true,questions:(await q(`SELECT * FROM questions ${w.length?"WHERE "+w.join(" AND "):""} ORDER BY id DESC`,p)).rows})});
app.get("/api/practicals",async(req,res)=>res.json({success:true,practicals:(await q("SELECT * FROM practicals ORDER BY id DESC")).rows}));
app.get("/api/exam-guides",async(req,res)=>res.json({success:true,guides:(await q("SELECT * FROM exam_guides ORDER BY id DESC")).rows}));

app.get("/api/courses",async(req,res)=>res.json({success:true,courses:(await q("SELECT * FROM courses WHERE published=TRUE ORDER BY id")).rows}));
app.get("/api/courses/:id/access",user,async(req,res)=>{if(req.user.role==="creator")return res.json({success:true,access:true,creator:true});const r=await q("SELECT * FROM enrollments WHERE user_id=$1 AND course_id::text=$2 AND status='active'",[req.user.id,req.params.id]);res.json({success:true,access:Boolean(r.rows[0]),enrollment:r.rows[0]||null})});
app.post("/api/payments/course",user,async(req,res)=>{try{const r=await q("SELECT * FROM courses WHERE id::text=$1 OR slug=$1",[String(req.body.courseId||"")]);const c=r.rows[0];if(!c)return res.status(404).json({success:false,message:"Course not found."});if(req.user.role==="creator"){await q("INSERT INTO enrollments(user_id,course_id,status) VALUES($1,$2,'active') ON CONFLICT(user_id,course_id) DO UPDATE SET status='active'",[req.user.id,c.id]);return res.json({success:true,enrolled:true,creator:true})}const ex=await q("SELECT 1 FROM enrollments WHERE user_id=$1 AND course_id=$2 AND status='active'",[req.user.id,c.id]);if(ex.rows[0])return res.json({success:true,enrolled:true});const ref=`PASSCOGH-COURSE-${crypto.randomUUID()}`;await q("INSERT INTO payments(user_id,item_type,item_id,amount_ghs,reference) VALUES($1,'course',$2,$3,$4)",[req.user.id,String(c.id),c.price_ghs,ref]);const base=process.env.PUBLIC_BASE_URL||`${req.protocol}://${req.get("host")}`;const pay=await paystackInit(req.user.email,c.price_ghs,ref,`${base}/payment/callback`);res.json({success:true,paymentRequired:true,authorizationUrl:pay.authorization_url,reference:ref})}catch(e){res.status(500).json({success:false,message:e.message})}});

app.get("/api/pdfs",async(req,res)=>res.json({success:true,pdfs:(await q("SELECT id,title,filename,storage_key,price_ghs,online_reading,paid_download,published FROM materials WHERE published=TRUE ORDER BY id")).rows}));
app.post("/api/reading/start",user,async(req,res)=>{const id=Number(req.body.pdfId||req.body.materialId),r=await q("SELECT * FROM materials WHERE id=$1 AND published=TRUE",[id]);const m=r.rows[0];if(!m)return res.status(404).json({success:false,message:"Material not found."});const raw=crypto.randomBytes(32).toString("hex"),hash=crypto.createHash("sha256").update(raw).digest("hex"),exp=new Date(Date.now()+30*60*1000);await q("INSERT INTO reading_sessions(user_id,material_id,token_hash,expires_at) VALUES($1,$2,$3,$4)",[req.user.id,m.id,hash,exp]);res.json({success:true,readingSessionToken:raw,expiresAt:exp.toISOString(),advertisementsEnabled:req.user.role!=="creator"})});
app.get("/api/pdfs/:id/download-access",user,async(req,res)=>{const m=(await q("SELECT * FROM materials WHERE id=$1",[req.params.id])).rows[0];if(!m)return res.status(404).json({success:false,message:"PDF not found."});if(req.user.role==="creator")return res.json({success:true,allowed:true,creator:true});const p=await q("SELECT 1 FROM material_purchases WHERE user_id=$1 AND material_id=$2",[req.user.id,m.id]);res.json({success:true,allowed:Boolean(p.rows[0])})});
app.post("/api/payments/pdf",user,async(req,res)=>{try{const id=Number(req.body.pdfId||req.body.materialId),m=(await q("SELECT * FROM materials WHERE id=$1 AND published=TRUE",[id])).rows[0];if(!m)return res.status(404).json({success:false,message:"PDF not found."});if(req.user.role==="creator")return res.json({success:true,downloadAllowed:true,creator:true});const ex=await q("SELECT 1 FROM material_purchases WHERE user_id=$1 AND material_id=$2",[req.user.id,m.id]);if(ex.rows[0])return res.json({success:true,downloadAllowed:true});const ref=`PASSCOGH-PDF-${crypto.randomUUID()}`;await q("INSERT INTO payments(user_id,item_type,item_id,amount_ghs,reference) VALUES($1,'material',$2,$3,$4)",[req.user.id,String(m.id),m.price_ghs,ref]);const base=process.env.PUBLIC_BASE_URL||`${req.protocol}://${req.get("host")}`;const pay=await paystackInit(req.user.email,m.price_ghs,ref,`${base}/payment/callback`);res.json({success:true,paymentRequired:true,authorizationUrl:pay.authorization_url,reference:ref})}catch(e){res.status(500).json({success:false,message:e.message})}});
app.get("/api/payments/verify/:reference",user,async(req,res)=>{try{const p=(await q("SELECT * FROM payments WHERE reference=$1 AND user_id=$2",[req.params.reference,req.user.id])).rows[0];if(!p)return res.status(404).json({success:false,message:"Payment record not found."});const t=await paystackVerify(p.reference);if(t.status!=="success"||t.currency!=="GHS"||Number(t.amount)!==Math.round(Number(p.amount_ghs)*100))return res.status(400).json({success:false,message:"Payment verification failed."});await q("UPDATE payments SET status='success',verified_at=NOW() WHERE id=$1",[p.id]);if(p.item_type==="course")await q("INSERT INTO enrollments(user_id,course_id,status) VALUES($1,$2,'active') ON CONFLICT(user_id,course_id) DO UPDATE SET status='active'",[p.user_id,Number(p.item_id)]);if(p.item_type==="material"||p.item_type==="pdf")await q("INSERT INTO material_purchases(user_id,material_id,payment_reference) VALUES($1,$2,$3) ON CONFLICT(user_id,material_id) DO NOTHING",[p.user_id,Number(p.item_id),p.reference]);res.json({success:true,verified:true,itemType:p.item_type,itemId:p.item_id})}catch(e){res.status(500).json({success:false,message:e.message})}});
app.get("/payment/callback",(req,res)=>res.send("<!doctype html><html><body style='font-family:system-ui;text-align:center;padding:30px'><h2>Payment received</h2><p>Return to PASSCOGH-MODOO to complete verification.</p></body></html>"));

app.post("/api/courses/:id/progress",user,async(req,res)=>{const n=Math.round(Number(req.body.progress));if(!Number.isFinite(n)||n<0||n>100)return res.status(400).json({success:false,message:"Progress must be between 0 and 100."});const c=(await q("SELECT * FROM courses WHERE id::text=$1 OR slug=$1",[req.params.id])).rows[0];if(!c)return res.status(404).json({success:false,message:"Course not found."});if(req.user.role!=="creator"&&!((await q("SELECT 1 FROM enrollments WHERE user_id=$1 AND course_id=$2 AND status='active'",[req.user.id,c.id])).rows[0]))return res.status(403).json({success:false,message:"You must be enrolled first."});await q("INSERT INTO enrollments(user_id,course_id,status,progress,completed_at) VALUES($1,$2,'active',$3,CASE WHEN $3=100 THEN NOW() ELSE NULL END) ON CONFLICT(user_id,course_id) DO UPDATE SET progress=EXCLUDED.progress,completed_at=EXCLUDED.completed_at",[req.user.id,c.id,n]);res.json({success:true,progress:n})});
app.post("/api/courses/:id/certificate",user,async(req,res)=>{const c=(await q("SELECT * FROM courses WHERE id::text=$1 OR slug=$1",[req.params.id])).rows[0];if(!c)return res.status(404).json({success:false,message:"Course not found."});const e=(await q("SELECT * FROM enrollments WHERE user_id=$1 AND course_id=$2 AND status='active'",[req.user.id,c.id])).rows[0];if(req.user.role!=="creator"&&(!e||e.progress<100))return res.status(403).json({success:false,message:"Complete the course before requesting a certificate."});const old=(await q("SELECT * FROM certificates WHERE user_id=$1 AND course_id=$2",[req.user.id,c.id])).rows[0];if(old)return res.json({success:true,certificate:old});const no=`PASSCOGH-${new Date().getFullYear()}-${crypto.randomBytes(5).toString("hex").toUpperCase()}`;const r=await q("INSERT INTO certificates(certificate_no,user_id,course_id) VALUES($1,$2,$3) RETURNING *",[no,req.user.id,c.id]);res.json({success:true,certificate:r.rows[0]})});
app.get("/api/certificates/:certificateNo",async(req,res)=>{const r=(await q("SELECT c.certificate_no,c.issued_at,u.name,u.email,co.title AS course_title FROM certificates c JOIN users u ON u.id=c.user_id JOIN courses co ON co.id=c.course_id WHERE c.certificate_no=$1",[req.params.certificateNo])).rows[0];if(!r)return res.status(404).json({success:false,valid:false,message:"Certificate not found."});res.json({success:true,valid:true,certificate:r})});

app.get("/api/creator/access",creator,(req,res)=>res.json({success:true,creator:true,role:"creator",unlimitedAccess:true,freeCourseAccess:true,freePdfDownload:true,advertisementsDisabled:true}));
app.get("/api/creator/dashboard",creator,async(req,res)=>{const [u,e,p,c]=await Promise.all([q("SELECT COUNT(*)::int count FROM users"),q("SELECT COUNT(*)::int count FROM enrollments"),q("SELECT COUNT(*)::int count FROM payments WHERE status='success'"),q("SELECT COUNT(*)::int count FROM certificates")]);res.json({success:true,users:u.rows[0].count,enrollments:e.rows[0].count,successfulPayments:p.rows[0].count,certificates:c.rows[0].count,curriculumFile:fs.existsSync(CURRICULUM_FILE)})});

app.use(express.static(PUBLIC_DIR));
app.get("*",(req,res)=>{const f=path.join(PUBLIC_DIR,"index.html");if(fs.existsSync(f))return res.sendFile(f);res.status(404).send("PASSCOGH-MODOO frontend not found.")});
app.use((err,req,res,next)=>{console.error(err);res.status(500).json({success:false,message:"PASSCOGH-MODOO server error."})});

async function start(){if(!process.env.DATABASE_URL)console.warn("DATABASE_URL is missing.");if(!JWT_SECRET)console.warn("JWT_SECRET is missing.");try{await q("SELECT 1");console.log("PostgreSQL connected.")}catch(e){console.error("PostgreSQL connection failed:",e.message)}app.listen(PORT,"0.0.0.0",()=>console.log(`PASSCOGH-MODOO running on port ${PORT}`))}
process.on("SIGTERM",async()=>{await pool.end();process.exit(0)});
start();
